from enum import Enum

class PathEnum(Enum):
    LEASE = "lease.ui"
    USERPW = "userPw.ui"
    SERVICE = "service.ui"
    TENANT = "tenant.ui"
    INSURANCE = "insurance.ui"
    PAYMENT = "payment.ui"
    CARDDETAILS = "card_details.ui"
    SYSTEMUSERNAME = "root"
    SYSTEMPASSWORD = "P@ssword123"
    DATABASENAME = "buildingmanagement1"
    HOSTNAME = "localhost"
    VIEWCARDDETAILS = "viewCardDetails.ui"
    DELETECARDDETAILS = "DeleteCardDetails.ui"
    VIEWBILLINGDETAILS = "viewBillingDetails.ui"
    ADDCARDDETAILS = "AddCardDetails.ui"
    INSURANCEDETAILS = "InsuranceDetails.ui"
    LEASEDETAILS = "LeaseDetails.ui"
    VIEWSERVICEDETAILS = "ViewServiceDetails.ui"
    RAISESERVICE = "RaiseService.ui"
    BUILDINGMANAGER = "BuildingManager.ui"
    LEASINGMANAGER = "LeasingManager.ui"
    HELPER = "Helper.ui"
    VIEWTENANTLEASING = "ViewTenantLeasing.ui"
    VIEWSERVICEHELPER = "ViewServiceHelper.ui"
    VIEW = "View.ui"
    UPDATESERVICEHELPER = "UpdateServiceHelper.ui"
    GENERATEBILL = "GenerateBill.ui"
    NEWCREDS = "new_creds.ui"
    ERROR = "error.ui"
    CREATEPW = "forgotPw.ui"
    NEWUSER = "NewUser.ui"
    ASSIGNSERVICE = "AssignService.ui"
    PAYBILL = "PayBill.ui"
    VISUALIZATION = "visualization.ui"
